version: "3.8"

networks:
  ls:
    name: ls

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    environment:
      - DEBUG=${DEBUG-1}
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - MAIN_DOCKER_NETWORK=ls
      - PERSISTENCE=${PERSISTENCE-}
    env_file:
      - ./.env.local
    image: "localstack/localstack-pro:${LOCALSTACK_VERSION-2.3.2}"
    networks:
      - ls
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:53:53" # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp" # DNS config (required for Pro)
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (required for Pro)
    volumes:
      - "$PWD/api/.esbuild/src/functions/hello/:$PWD/api/build/hot"
      - "/var/run/docker.sock:/var/run/docker.sock"
