version: "3.8"

networks:
  ls:
    name: ls

services:
  bar:
    container_name: "bar"
    env_file:
      - ../../.env.local
    environment:
      - AWS_RDS_HOSTNAME=localstack
    image: docker.io/bitnami/express:4
    networks:
      - ls
    ports:
      - 3001:3000
    volumes:
      - ".:/app"