version: "3.8"

networks:
  ls:
    name: ls

services:
  apollo:
    container_name: "router"
    environment:
      - APOLLO_ROUTER_CONFIG_PATH=/dist/config/router.yaml
      - APOLLO_ROUTER_HOT_RELOAD=true
      - APOLLO_ROUTER_SUPERGRAPH_PATH=/dist/config/supergraph.graphql
    image: "ghcr.io/apollographql/router:${APOLLO_ROUTER_VERSION-v1.34.0}"
    networks:
      - ls
    ports:
      - 8000:4000
    volumes:
      - "./router.yaml:/dist/config/router.yaml"
      - "./supergraph.graphql:/dist/config/supergraph.graphql"
      - "/var/run/docker.sock:/var/run/docker.sock"
